# mkdocs.yml
site_name: Trappy-Scopes
site_url: https://trappy-scopes.github.io/
repo_url: https://github.com/Trappy-Scopes/

nav:
  - Home: README.md
  - scope-cli: https://trappy-scopes.github.io/trappyscopes

plugins:
  - search
  - blogging
#  - autorefs
#  - redirects
      

extra:
  homepage: https://trappy-scopes.github.io/

theme:
  logo: assets/tsicon.png
  name: material
  palette:
    # Dark mode as default
    - scheme: slate
      primary: deep purple
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    # Light mode option
    - scheme: default
      primary: indigo
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
  features:
    - navigation.tabs
    - navigation.top
    - navigation.indexes
    - toc.integrate
    - search.highlight
    - content.code.annotate
    - content.code.copy

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight
  - attr_list
  - md_in_html
  - tables
  - pymdownx.superfences